name: PowerMining
main: org.bitbucket.bloodyshade.PowerMining
version: 2.6.1
author: BloodyShade
description: Implements Hammer and Excavator tools for faster mining

permissions:
    powermining.*:
        description: Grants all permissions
        children:
            powermining.craft: true
            powermining.use: true
    powermining.craft:
        description: Allows players to craft the Hammer and Excavator tools
        default: true
    powermining.use:
        description: Allows players to use the Hammer and Excavator tools
        default: true