name: PowerMining
main: org.bitbucket.bloodyshade.PowerMining
version: 2.6
author: BloodyShade
description: Implements Hammer and Excavator tools for faster mining

permissions:
    powermining.*:
        description: Grants all permissions
        children:
            powermining.craft: true
    powermining.craft:
        description: Allows players to craft the Hammer and Excavator tools
        default: true